name: build

on:
  schedule:
    - cron: '0 14 * * SAT'
  push:
    branches:
     - master
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: tests/shunit2

      - name: Build alpine image
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile-alpine \
            --tag="$IMAGE_NAME:alpine" \
            --tag="ghcr.io/$IMAGE_NAME:alpine" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test alpine image
        run: tests/run $IMAGE_NAME:alpine
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push image
        run: docker push ghcr.io/$IMAGE_NAME:alpine     
